// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type HostInitParameters struct {

	// (String) Description for the host
	// Description for the host
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) Denotes if the host is online and is available
	// Denotes if the host is online and is available
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Set of Number) The list of groups to assosicate with a host.
	// The list of groups to assosicate with a host.
	// +listType=set
	Groups []*float64 `json:"groups,omitempty" tf:"groups,omitempty"`

	// (Number) Inventory id
	// Inventory id
	InventoryID *float64 `json:"inventoryId,omitempty" tf:"inventory_id,omitempty"`

	// (String) Name of the host
	// Name of the host
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Variables for the host configuration. Must be provided as either a JSON or YAML string.
	// Variables for the host configuration. Must be provided as either a JSON or YAML string.
	Variables *string `json:"variables,omitempty" tf:"variables,omitempty"`
}

type HostObservation struct {

	// (String) Description for the host
	// Description for the host
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) Denotes if the host is online and is available
	// Denotes if the host is online and is available
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Set of Number) The list of groups to assosicate with a host.
	// The list of groups to assosicate with a host.
	// +listType=set
	Groups []*float64 `json:"groups,omitempty" tf:"groups,omitempty"`

	// (Number) ID of the host
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Number) Inventory id
	// Inventory id
	InventoryID *float64 `json:"inventoryId,omitempty" tf:"inventory_id,omitempty"`

	// (String) Name of the host
	// Name of the host
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) URL of the host
	// URL of the host
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// (String) Variables for the host configuration. Must be provided as either a JSON or YAML string.
	// Variables for the host configuration. Must be provided as either a JSON or YAML string.
	Variables *string `json:"variables,omitempty" tf:"variables,omitempty"`
}

type HostParameters struct {

	// (String) Description for the host
	// Description for the host
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) Denotes if the host is online and is available
	// Denotes if the host is online and is available
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Set of Number) The list of groups to assosicate with a host.
	// The list of groups to assosicate with a host.
	// +kubebuilder:validation:Optional
	// +listType=set
	Groups []*float64 `json:"groups,omitempty" tf:"groups,omitempty"`

	// (Number) Inventory id
	// Inventory id
	// +kubebuilder:validation:Optional
	InventoryID *float64 `json:"inventoryId,omitempty" tf:"inventory_id,omitempty"`

	// (String) Name of the host
	// Name of the host
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Variables for the host configuration. Must be provided as either a JSON or YAML string.
	// Variables for the host configuration. Must be provided as either a JSON or YAML string.
	// +kubebuilder:validation:Optional
	Variables *string `json:"variables,omitempty" tf:"variables,omitempty"`
}

// HostSpec defines the desired state of Host
type HostSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            HostParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider HostInitParameters `json:"initProvider,omitempty"`
}

// HostStatus defines the observed state of Host.
type HostStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        HostObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Host is the Schema for the Hosts API. Creates a host.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,aap}
type Host struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.inventoryId) || (has(self.initProvider) && has(self.initProvider.inventoryId))",message="spec.forProvider.inventoryId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   HostSpec   `json:"spec"`
	Status HostStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// HostList contains a list of Hosts
type HostList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Host `json:"items"`
}

// Repository type metadata.
var (
	Host_Kind             = "Host"
	Host_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Host_Kind}.String()
	Host_KindAPIVersion   = Host_Kind + "." + CRDGroupVersion.String()
	Host_GroupVersionKind = CRDGroupVersion.WithKind(Host_Kind)
)

func init() {
	SchemeBuilder.Register(&Host{}, &HostList{})
}
