// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type InventoryInitParameters struct {

	// (String) Description for the inventory
	// Description for the inventory
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Name of the inventory
	// Name of the inventory
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Identifier for the organization the inventory should be created in. If not provided, the inventory will be created in the default organization. NOTICE the organization attribute will be required in release 2.0.0
	// Identifier for the organization the inventory should be created in. If not provided, the inventory will be created in the default organization. NOTICE the organization attribute will be required in release 2.0.0
	Organization *float64 `json:"organization,omitempty" tf:"organization,omitempty"`

	// (String) Inventory variables. Must be provided as either a JSON or YAML string.
	// Inventory variables. Must be provided as either a JSON or YAML string.
	Variables *string `json:"variables,omitempty" tf:"variables,omitempty"`
}

type InventoryObservation struct {

	// (String) Description for the inventory
	// Description for the inventory
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Number) Inventory id
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Name of the inventory
	// Name of the inventory
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Named URL of the inventory
	// Named URL of the inventory
	NamedURL *string `json:"namedUrl,omitempty" tf:"named_url,omitempty"`

	// (Number) Identifier for the organization the inventory should be created in. If not provided, the inventory will be created in the default organization. NOTICE the organization attribute will be required in release 2.0.0
	// Identifier for the organization the inventory should be created in. If not provided, the inventory will be created in the default organization. NOTICE the organization attribute will be required in release 2.0.0
	Organization *float64 `json:"organization,omitempty" tf:"organization,omitempty"`

	// (String) Name for the organization.
	// Name for the organization.
	OrganizationName *string `json:"organizationName,omitempty" tf:"organization_name,omitempty"`

	// (String) URL of the inventory
	// URL of the inventory
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// (String) Inventory variables. Must be provided as either a JSON or YAML string.
	// Inventory variables. Must be provided as either a JSON or YAML string.
	Variables *string `json:"variables,omitempty" tf:"variables,omitempty"`
}

type InventoryParameters struct {

	// (String) Description for the inventory
	// Description for the inventory
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Name of the inventory
	// Name of the inventory
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Identifier for the organization the inventory should be created in. If not provided, the inventory will be created in the default organization. NOTICE the organization attribute will be required in release 2.0.0
	// Identifier for the organization the inventory should be created in. If not provided, the inventory will be created in the default organization. NOTICE the organization attribute will be required in release 2.0.0
	// +kubebuilder:validation:Optional
	Organization *float64 `json:"organization,omitempty" tf:"organization,omitempty"`

	// (String) Inventory variables. Must be provided as either a JSON or YAML string.
	// Inventory variables. Must be provided as either a JSON or YAML string.
	// +kubebuilder:validation:Optional
	Variables *string `json:"variables,omitempty" tf:"variables,omitempty"`
}

// InventorySpec defines the desired state of Inventory
type InventorySpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            InventoryParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider InventoryInitParameters `json:"initProvider,omitempty"`
}

// InventoryStatus defines the observed state of Inventory.
type InventoryStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        InventoryObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Inventory is the Schema for the Inventorys API. Creates an inventory.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,aap}
type Inventory struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   InventorySpec   `json:"spec"`
	Status InventoryStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// InventoryList contains a list of Inventorys
type InventoryList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Inventory `json:"items"`
}

// Repository type metadata.
var (
	Inventory_Kind             = "Inventory"
	Inventory_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Inventory_Kind}.String()
	Inventory_KindAPIVersion   = Inventory_Kind + "." + CRDGroupVersion.String()
	Inventory_GroupVersionKind = CRDGroupVersion.WithKind(Inventory_Kind)
)

func init() {
	SchemeBuilder.Register(&Inventory{}, &InventoryList{})
}
