// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type WorkflowJobInitParameters struct {

	// (String) Extra Variables. Must be provided as either a JSON or YAML string.
	// Extra Variables. Must be provided as either a JSON or YAML string.
	ExtraVars *string `json:"extraVars,omitempty" tf:"extra_vars,omitempty"`

	// (Number) Identifier for the inventory the job will be run against.
	// Identifier for the inventory the job will be run against.
	InventoryID *float64 `json:"inventoryId,omitempty" tf:"inventory_id,omitempty"`

	// (Map of String) Map of arbitrary keys and values that, when changed, will trigger a creation of a new Workflow Job on AAP.
	// Map of arbitrary keys and values that, when changed, will trigger a creation of a new Workflow Job on AAP.
	// +mapType=granular
	Triggers map[string]*string `json:"triggers,omitempty" tf:"triggers,omitempty"`

	// (Number) ID of the workflow job template.
	// ID of the workflow job template.
	WorkflowJobTemplateID *float64 `json:"workflowJobTemplateId,omitempty" tf:"workflow_job_template_id,omitempty"`
}

type WorkflowJobObservation struct {

	// (String) Extra Variables. Must be provided as either a JSON or YAML string.
	// Extra Variables. Must be provided as either a JSON or YAML string.
	ExtraVars *string `json:"extraVars,omitempty" tf:"extra_vars,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (List of String) The list of properties set by the user but ignored on server side.
	// The list of properties set by the user but ignored on server side.
	IgnoredFields []*string `json:"ignoredFields,omitempty" tf:"ignored_fields,omitempty"`

	// (Number) Identifier for the inventory the job will be run against.
	// Identifier for the inventory the job will be run against.
	InventoryID *float64 `json:"inventoryId,omitempty" tf:"inventory_id,omitempty"`

	// (String) Job type
	// Job type
	JobType *string `json:"jobType,omitempty" tf:"job_type,omitempty"`

	// (String) Status of the workflow job
	// Status of the workflow job
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (Map of String) Map of arbitrary keys and values that, when changed, will trigger a creation of a new Workflow Job on AAP.
	// Map of arbitrary keys and values that, when changed, will trigger a creation of a new Workflow Job on AAP.
	// +mapType=granular
	Triggers map[string]*string `json:"triggers,omitempty" tf:"triggers,omitempty"`

	// (String) URL of the workflow job template
	// URL of the workflow job template
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// (Number) ID of the workflow job template.
	// ID of the workflow job template.
	WorkflowJobTemplateID *float64 `json:"workflowJobTemplateId,omitempty" tf:"workflow_job_template_id,omitempty"`
}

type WorkflowJobParameters struct {

	// (String) Extra Variables. Must be provided as either a JSON or YAML string.
	// Extra Variables. Must be provided as either a JSON or YAML string.
	// +kubebuilder:validation:Optional
	ExtraVars *string `json:"extraVars,omitempty" tf:"extra_vars,omitempty"`

	// (Number) Identifier for the inventory the job will be run against.
	// Identifier for the inventory the job will be run against.
	// +kubebuilder:validation:Optional
	InventoryID *float64 `json:"inventoryId,omitempty" tf:"inventory_id,omitempty"`

	// (Map of String) Map of arbitrary keys and values that, when changed, will trigger a creation of a new Workflow Job on AAP.
	// Map of arbitrary keys and values that, when changed, will trigger a creation of a new Workflow Job on AAP.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Triggers map[string]*string `json:"triggers,omitempty" tf:"triggers,omitempty"`

	// (Number) ID of the workflow job template.
	// ID of the workflow job template.
	// +kubebuilder:validation:Optional
	WorkflowJobTemplateID *float64 `json:"workflowJobTemplateId,omitempty" tf:"workflow_job_template_id,omitempty"`
}

// WorkflowJobSpec defines the desired state of WorkflowJob
type WorkflowJobSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            WorkflowJobParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider WorkflowJobInitParameters `json:"initProvider,omitempty"`
}

// WorkflowJobStatus defines the observed state of WorkflowJob.
type WorkflowJobStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        WorkflowJobObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// WorkflowJob is the Schema for the WorkflowJobs API. Launches an AAP workflow job. A workflow job is launched only when the resource is first created or when the resource is changed. The triggers argument can be used to launch a new workflow job based on any arbitrary value. This resource always creates a new workflow job in AAP. A destroy will not delete a workflow job created by this resource, it will only remove the resource from the state.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,aap}
type WorkflowJob struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.workflowJobTemplateId) || (has(self.initProvider) && has(self.initProvider.workflowJobTemplateId))",message="spec.forProvider.workflowJobTemplateId is a required parameter"
	Spec   WorkflowJobSpec   `json:"spec"`
	Status WorkflowJobStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// WorkflowJobList contains a list of WorkflowJobs
type WorkflowJobList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []WorkflowJob `json:"items"`
}

// Repository type metadata.
var (
	WorkflowJob_Kind             = "WorkflowJob"
	WorkflowJob_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: WorkflowJob_Kind}.String()
	WorkflowJob_KindAPIVersion   = WorkflowJob_Kind + "." + CRDGroupVersion.String()
	WorkflowJob_GroupVersionKind = CRDGroupVersion.WithKind(WorkflowJob_Kind)
)

func init() {
	SchemeBuilder.Register(&WorkflowJob{}, &WorkflowJobList{})
}
