apiVersion: core.aap.m.crossplane.io/v1alpha1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: core/v1alpha1/group
  labels:
    testing.upbound.io/example-name: sample_foo
  name: sample-foo
  namespace: crossplane-system
spec:
  forProvider:
    inventoryId: ${aap_inventory.my_inventory.id}
    name: tf_group_foo
    variables: '${jsonencode({ "ansible_network_os" : "ios" })}'

---

apiVersion: core.aap.m.crossplane.io/v1alpha1
kind: Inventory
metadata:
  annotations:
    meta.upbound.io/example-id: core/v1alpha1/group
  labels:
    testing.upbound.io/example-name: my_inventory
  name: my-inventory
  namespace: crossplane-system
spec:
  forProvider:
    name: A new inventory
    organization: 1
