// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type JobInitParameters struct {

	// (String) Extra Variables. Must be provided as either a JSON or YAML string.
	// Extra Variables. Must be provided as either a JSON or YAML string.
	ExtraVars *string `json:"extraVars,omitempty" tf:"extra_vars,omitempty"`

	// (Number) Identifier for the inventory where job should be created in. If not provided, the job will be created in the default inventory.
	// Identifier for the inventory where job should be created in. If not provided, the job will be created in the default inventory.
	InventoryID *float64 `json:"inventoryId,omitempty" tf:"inventory_id,omitempty"`

	// (Number) ID of the job template.
	// ID of the job template.
	JobTemplateID *float64 `json:"jobTemplateId,omitempty" tf:"job_template_id,omitempty"`

	// (Map of String) Map of arbitrary keys and values that, when changed, will trigger a creation of a new Job on AAP.
	// Map of arbitrary keys and values that, when changed, will trigger a creation of a new Job on AAP.
	// +mapType=granular
	Triggers map[string]*string `json:"triggers,omitempty" tf:"triggers,omitempty"`

	// (boolean) when this is set to true, provider will wait until this aap_job resource is created, reaches any final status and then, proceeds with the following resource operation
	// when this is set to `true`, provider will wait until this aap_job resource is created, reaches any final status and then, proceeds with the following resource operation
	WaitForCompletion *bool `json:"waitForCompletion,omitempty" tf:"wait_for_completion,omitempty"`

	// Default value of `120`
	WaitForCompletionTimeoutSeconds *float64 `json:"waitForCompletionTimeoutSeconds,omitempty" tf:"wait_for_completion_timeout_seconds,omitempty"`
}

type JobObservation struct {

	// (String) Extra Variables. Must be provided as either a JSON or YAML string.
	// Extra Variables. Must be provided as either a JSON or YAML string.
	ExtraVars *string `json:"extraVars,omitempty" tf:"extra_vars,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (List of String) The list of properties set by the user but ignored on server side.
	// The list of properties set by the user but ignored on server side.
	IgnoredFields []*string `json:"ignoredFields,omitempty" tf:"ignored_fields,omitempty"`

	// (Number) Identifier for the inventory where job should be created in. If not provided, the job will be created in the default inventory.
	// Identifier for the inventory where job should be created in. If not provided, the job will be created in the default inventory.
	InventoryID *float64 `json:"inventoryId,omitempty" tf:"inventory_id,omitempty"`

	// (Number) ID of the job template.
	// ID of the job template.
	JobTemplateID *float64 `json:"jobTemplateId,omitempty" tf:"job_template_id,omitempty"`

	// (String) Job type
	// Job type
	JobType *string `json:"jobType,omitempty" tf:"job_type,omitempty"`

	// (String) Status of the job
	// Status of the job
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (Map of String) Map of arbitrary keys and values that, when changed, will trigger a creation of a new Job on AAP.
	// Map of arbitrary keys and values that, when changed, will trigger a creation of a new Job on AAP.
	// +mapType=granular
	Triggers map[string]*string `json:"triggers,omitempty" tf:"triggers,omitempty"`

	// (String) URL of the job template
	// URL of the job template
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// (boolean) when this is set to true, provider will wait until this aap_job resource is created, reaches any final status and then, proceeds with the following resource operation
	// when this is set to `true`, provider will wait until this aap_job resource is created, reaches any final status and then, proceeds with the following resource operation
	WaitForCompletion *bool `json:"waitForCompletion,omitempty" tf:"wait_for_completion,omitempty"`

	// Default value of `120`
	WaitForCompletionTimeoutSeconds *float64 `json:"waitForCompletionTimeoutSeconds,omitempty" tf:"wait_for_completion_timeout_seconds,omitempty"`
}

type JobParameters struct {

	// (String) Extra Variables. Must be provided as either a JSON or YAML string.
	// Extra Variables. Must be provided as either a JSON or YAML string.
	// +kubebuilder:validation:Optional
	ExtraVars *string `json:"extraVars,omitempty" tf:"extra_vars,omitempty"`

	// (Number) Identifier for the inventory where job should be created in. If not provided, the job will be created in the default inventory.
	// Identifier for the inventory where job should be created in. If not provided, the job will be created in the default inventory.
	// +kubebuilder:validation:Optional
	InventoryID *float64 `json:"inventoryId,omitempty" tf:"inventory_id,omitempty"`

	// (Number) ID of the job template.
	// ID of the job template.
	// +kubebuilder:validation:Optional
	JobTemplateID *float64 `json:"jobTemplateId,omitempty" tf:"job_template_id,omitempty"`

	// (Map of String) Map of arbitrary keys and values that, when changed, will trigger a creation of a new Job on AAP.
	// Map of arbitrary keys and values that, when changed, will trigger a creation of a new Job on AAP.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Triggers map[string]*string `json:"triggers,omitempty" tf:"triggers,omitempty"`

	// (boolean) when this is set to true, provider will wait until this aap_job resource is created, reaches any final status and then, proceeds with the following resource operation
	// when this is set to `true`, provider will wait until this aap_job resource is created, reaches any final status and then, proceeds with the following resource operation
	// +kubebuilder:validation:Optional
	WaitForCompletion *bool `json:"waitForCompletion,omitempty" tf:"wait_for_completion,omitempty"`

	// Default value of `120`
	// +kubebuilder:validation:Optional
	WaitForCompletionTimeoutSeconds *float64 `json:"waitForCompletionTimeoutSeconds,omitempty" tf:"wait_for_completion_timeout_seconds,omitempty"`
}

// JobSpec defines the desired state of Job
type JobSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     JobParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider JobInitParameters `json:"initProvider,omitempty"`
}

// JobStatus defines the observed state of Job.
type JobStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        JobObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Job is the Schema for the Jobs API. Launches an AAP job. A job is launched only when the resource is first created or when the resource is changed. The triggers argument can be used to launch a new job based on any arbitrary value. This resource always creates a new job in AAP. A destroy will not delete a job created by this resource, it will only remove the resource from the state. This parameter works in both create and update operations. You can also tweak wait_for_completion_timeout_seconds to control the timeout limit.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,aap}
type Job struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.jobTemplateId) || (has(self.initProvider) && has(self.initProvider.jobTemplateId))",message="spec.forProvider.jobTemplateId is a required parameter"
	Spec   JobSpec   `json:"spec"`
	Status JobStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// JobList contains a list of Jobs
type JobList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Job `json:"items"`
}

// Repository type metadata.
var (
	Job_Kind             = "Job"
	Job_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Job_Kind}.String()
	Job_KindAPIVersion   = Job_Kind + "." + CRDGroupVersion.String()
	Job_GroupVersionKind = CRDGroupVersion.WithKind(Job_Kind)
)

func init() {
	SchemeBuilder.Register(&Job{}, &JobList{})
}
